version: 2
updates:

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: monthly
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: '02:00'
  open-pull-requests-limit: 15
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: '02:00'
  open-pull-requests-limit: 15
