ame-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed
  $CHANGES
categories:
  - title: 'Dependency Updates'
    labels:
      - dependencies

exclude-labels:
  - 'skip-changelog'
